In [41]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [42]:
from google.colab import files
uploaded = files.upload()

Saving data_preprocessed.csv to data_preprocessed (1).csv


# Load the Data

In [43]:
df = pd.read_csv('data_preprocessed.csv')
df.head()
df.columns.values
df = df.drop(['Unnamed: 0','Date'],axis=1)
df.head()

Reason_1  Reason_2  Reason_3  ...  Children  Pets  Absenteeism Time in Hours
0         0         0         0  ...         2     1                          4
1         0         0         0  ...         1     0                          0
2         0         0         0  ...         0     0                          2
3         1         0         0  ...         2     0                          4
4         0         0         0  ...         2     1                          2

[5 rows x 15 columns]

# Create the Target

In [44]:
df['Absenteeism Time in Hours'].median() 
# >3 - excessively absent  
# <3 - moderately absent

3.0

In [45]:
target = np.where(df['Absenteeism Time in Hours'] > df['Absenteeism Time in Hours'].median(),1,0)
target

array([1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0,
       1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1,
       0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1,
       0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0,
       1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1,
       1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0,
       0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0,
       0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0,

In [46]:
df['Excessive Absenteeism'] = target
df.head()

Reason_1  Reason_2  ...  Absenteeism Time in Hours  Excessive Absenteeism
0         0         0  ...                          4                      1
1         0         0  ...                          0                      0
2         0         0  ...                          2                      0
3         1         0  ...                          4                      1
4         0         0  ...                          2                      0

[5 rows x 16 columns]

In [47]:
df.shape

(700, 16)

In [48]:
df.drop(['Absenteeism Time in Hours'],axis=1)
df.head()

Reason_1  Reason_2  ...  Absenteeism Time in Hours  Excessive Absenteeism
0         0         0  ...                          4                      1
1         0         0  ...                          0                      0
2         0         0  ...                          2                      0
3         1         0  ...                          4                      1
4         0         0  ...                          2                      0

[5 rows x 16 columns]

In [49]:
df.iloc[:, :14]

Reason_1  Reason_2  Reason_3  ...  Education  Children  Pets
0           0         0         0  ...          0         2     1
1           0         0         0  ...          0         1     0
2           0         0         0  ...          0         0     0
3           1         0         0  ...          0         2     0
4           0         0         0  ...          0         2     1
..        ...       ...       ...  ...        ...       ...   ...
695         1         0         0  ...          1         2     0
696         1         0         0  ...          0         1     2
697         1         0         0  ...          1         0     0
698         0         0         0  ...          1         0     0
699         0         0         0  ...          0         1     1

[700 rows x 14 columns]

In [50]:
unscaled_inputs = df.iloc[:, :14]

# Standardization of Data

In [51]:
from sklearn.preprocessing import StandardScaler

In [52]:
scaler = StandardScaler()

In [53]:
scaler.fit(unscaled_inputs)

StandardScaler(copy=True, with_mean=True, with_std=True)

In [54]:
scaled_inputs = scaler.transform(unscaled_inputs) # subtract mean and divide by Standard deviation

In [55]:
scaled_inputs.shape

(700, 14)

# Train-Test Split

In [56]:
from sklearn.model_selection import train_test_split

In [57]:
X = scaled_inputs
y = target

In [58]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [59]:
X_train.shape, X_test.shape

((560, 14), (140, 14))

In [60]:
y_train.shape, y_test.shape

((560,), (140,))

# Models

In [61]:
from sklearn.linear_model import LogisticRegression
from sklearn import metrics

In [62]:
log_reg = LogisticRegression()

In [63]:
log_reg.fit(X_train, y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=None, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

In [64]:
log_reg.score(X_train,y_train)

0.7732142857142857

In [65]:
model_output = log_reg.predict(X_train)

In [66]:
model_output

array([1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0,
       0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1,
       0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1,
       1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0,
       1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0,
       0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0,
       0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0,
       1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0,
       1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1,
       1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1,
       0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1,
       0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0,
       1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0,

In [67]:
# model_output == y_train

In [68]:
np.sum((model_output == y_train))

433

In [69]:
model_output.shape

(560,)

In [70]:
np.sum((model_output == y_train)) / model_output.shape[0]

0.7732142857142857

# Finding coefficient and intercept

In [71]:
log_reg.intercept_

array([-0.1807155])

In [72]:
log_reg.coef_

array([[ 2.1388561 ,  0.34702326,  1.53810153,  1.41264252,  0.09468983,
        -0.15167965,  0.79489979, -0.09787614, -0.28710602, -0.01114994,
         0.28400839, -0.14757032,  0.4228082 , -0.36512155]])

In [73]:
feature_name = unscaled_inputs.columns.values
feature_name

array(['Reason_1', 'Reason_2', 'Reason_3', 'Reason_4', 'Month', 'Weekday',
       'Transportation Expense', 'Distance to Work', 'Age',
       'Daily Work Load Average', 'Body Mass Index', 'Education',
       'Children', 'Pets'], dtype=object)

In [74]:
summary_table = pd.DataFrame(columns=['Feature Name'],data=feature_name)
summary_table['Coefficient'] = np.transpose(log_reg.coef_)
summary_table

Feature Name  Coefficient
0                  Reason_1     2.138856
1                  Reason_2     0.347023
2                  Reason_3     1.538102
3                  Reason_4     1.412643
4                     Month     0.094690
5                   Weekday    -0.151680
6    Transportation Expense     0.794900
7          Distance to Work    -0.097876
8                       Age    -0.287106
9   Daily Work Load Average    -0.011150
10          Body Mass Index     0.284008
11                Education    -0.147570
12                 Children     0.422808
13                     Pets    -0.365122

In [80]:
summary_table.index = summary_table.index + 1
summary_table.loc[0] = ['Intercept', log_reg.intercept_[0]]
summary_table = summary_table.sort_index()
summary_table.sort_values('Coefficient',ascending=False)

Feature Name  Coefficient
6                  Reason_1     2.138856
8                  Reason_3     1.538102
9                  Reason_4     1.412643
12   Transportation Expense     0.794900
18                 Children     0.422808
7                  Reason_2     0.347023
16          Body Mass Index     0.284008
10                    Month     0.094690
15  Daily Work Load Average    -0.011150
13         Distance to Work    -0.097876
17                Education    -0.147570
11                  Weekday    -0.151680
0                 Intercept    -0.180715
1                 Intercept    -0.180715
5                 Intercept    -0.180715
4                 Intercept    -0.180715
3                 Intercept    -0.180715
2                 Intercept    -0.180715
14                      Age    -0.287106
19                     Pets    -0.365122

# Backward Elimination

removing all the features which have close to no contribution to the model 

# Test Data

In [83]:
log_reg.score(X_test,y_test)

0.7571428571428571

In [84]:
predicted_proba = log_reg.predict_proba(X_test)
predicted_proba 
# first column - 0 
# second column - 1
# summation horizontally will be 1

array([[0.6413989 , 0.3586011 ],
       [0.89337584, 0.10662416],
       [0.80816933, 0.19183067],
       [0.56110816, 0.43889184],
       [0.48607108, 0.51392892],
       [0.06333152, 0.93666848],
       [0.64709711, 0.35290289],
       [0.30969269, 0.69030731],
       [0.94314245, 0.05685755],
       [0.72233253, 0.27766747],
       [0.90521482, 0.09478518],
       [0.68665101, 0.31334899],
       [0.23736224, 0.76263776],
       [0.48452815, 0.51547185],
       [0.74799777, 0.25200223],
       [0.47177326, 0.52822674],
       [0.98803103, 0.01196897],
       [0.21765353, 0.78234647],
       [0.90694384, 0.09305616],
       [0.5743755 , 0.4256245 ],
       [0.68333932, 0.31666068],
       [0.78649197, 0.21350803],
       [0.67252453, 0.32747547],
       [0.66900989, 0.33099011],
       [0.88092293, 0.11907707],
       [0.15382488, 0.84617512],
       [0.58541016, 0.41458984],
       [0.88043436, 0.11956564],
       [0.80370549, 0.19629451],
       [0.60183417, 0.39816583],
       [0.

In [85]:
predicted_proba[:,1]

array([0.3586011 , 0.10662416, 0.19183067, 0.43889184, 0.51392892,
       0.93666848, 0.35290289, 0.69030731, 0.05685755, 0.27766747,
       0.09478518, 0.31334899, 0.76263776, 0.51547185, 0.25200223,
       0.52822674, 0.01196897, 0.78234647, 0.09305616, 0.4256245 ,
       0.31666068, 0.21350803, 0.32747547, 0.33099011, 0.11907707,
       0.84617512, 0.41458984, 0.11956564, 0.19629451, 0.39816583,
       0.10002532, 0.14028923, 0.60910734, 0.57904521, 0.23406737,
       0.68509422, 0.28400331, 0.14353399, 0.91936556, 0.1632639 ,
       0.53961947, 0.22795596, 0.58350813, 0.12495925, 0.18198628,
       0.76430208, 0.85484358, 0.92416908, 0.33992865, 0.11725058,
       0.22034488, 0.31998252, 0.46381103, 0.95359774, 0.15017929,
       0.2323032 , 0.985013  , 0.27280825, 0.90206204, 0.49598824,
       0.60954506, 0.12466075, 0.58158133, 0.69099541, 0.09478518,
       0.1137948 , 0.68391277, 0.00936286, 0.28449038, 0.48408005,
       0.27766747, 0.21465088, 0.76993826, 0.31998252, 0.10527

# Save the Model

In [86]:
import pickle

In [87]:
with open('model','wb') as file:
  pickle.dump(log_reg,file)